# -*- coding: utf-8 -*-
"""Abu_Python_Project_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1phgA1Ui-sELitEeN-thADMiWTdhuUDMt
"""

# The goal of this project is to analyze NYPD arrest data

# Commented out IPython magic to ensure Python compatibility.
# Load necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
import timeit
import io

from google.colab import drive
# Mount google drive
drive.mount('/content/mydrive')

# Load the data set
df=pd.read_csv('/content/mydrive/MyDrive/NYPD_Arrest_Data_(Year_to_Date)_20251215.csv')

#view data
df.head()

df.columns

df.shape

df.count()

#sort by precinct
df.sort_values(by='ARREST_PRECINCT', ascending=True)

df.describe()

#check for mising values
df.isnull().sum()

#Pick any zip code/neighborhood/district in this dataset as an initial comparison point
#ARREST_PRECINCT = 94th Precint (Greenpoint - current neighborhood)
#Pick a feature/measure/column
#ARREST_KEY = Randomly generated persistent ID for each arrest / can be used as count
#PERP_RACE AND PERP_SEX
#Which Sex and Race dominates the arrests in Greenpoin, Brooklyn

#create smaller data frame based upon above
df2 = df[['ARREST_PRECINCT', 'PERP_RACE', 'PERP_SEX', 'ARREST_KEY' ]]
df2.head()
df2.sort_values(by='ARREST_PRECINCT', ascending=True)

#check for missing values in data frame
df2.isnull().sum()

#choose one precint only = Precint 94
df3=df2.loc[df2['ARREST_PRECINCT'].isin([94])]

df3.shape

df3.head()

#visualize race arrest numbers using arrest key as count
df3.groupby(['PERP_RACE'])['ARREST_KEY'].count().sort_values(ascending=False).plot(kind='bar')

#visualize arrest by sex numbers using arrest key as count
df3.groupby(['PERP_SEX'])['ARREST_KEY'].count().sort_values(ascending=False).plot(kind='bar')

#more visualizing race and sex arrests; borrowed code from classmate - race should be veritical
sns.displot(data=df3, x="PERP_RACE", col="PERP_SEX", hue="PERP_RACE")

#changing arrest precing value from interger to string b/c had weird error that turned out to be a typo of precinct but left change
df3['ARREST_PRECINCT'] = df['ARREST_PRECINCT'].astype("string")

#renamed 94th precinct as greenpoint, wrong df
df.loc[df['ARREST_PRECINCT'] == 94, 'ARREST_PRECINCT'] = 'Greenpoint'

df3.loc[df3['ARREST_PRECINCT'] == 94, 'ARREST_PRECINCT'] = 'Greenpoint'

#trying to visualize both race and sex which appear on peripheral bar charts but not internal scatter
sns.jointplot(x='PERP_SEX', y='PERP_RACE', data=df3)

#visualize race arrests as bar - correct number counts
sns.displot(df3['PERP_RACE'])

#tried flipping race and sex, scatter still off, bars appear correct
sns.jointplot(x='PERP_RACE', y='PERP_SEX', data=df3)

#visualizing arrests by sex, counts are correct
sns.displot(df3['PERP_SEX'])

#groupby confirmation of counts
df3.groupby(['PERP_SEX'])['PERP_SEX'].count().sort_values(ascending=False)

#groupby confirmation of counts
df3.groupby(['PERP_RACE'])['PERP_RACE'].count().sort_values(ascending=False)

#attempting to visualize both sex and race; hue works to break out race; perp sex axis is fine but unique arrest key which worked for prior counts is now skewed???
sns.barplot(x="PERP_SEX", y="ARREST_KEY", hue="PERP_RACE", data=df3)

#arrest key still skewed
sns.barplot(x="PERP_RACE", y="ARREST_KEY", hue="PERP_SEX", data=df3)

#visualization appears to represent earlier groupby counts but unique arrest key still skewed
sns.pairplot(df3, hue = 'PERP_RACE')

sns.pairplot(df3, hue = 'PERP_SEX')

#look at citywide arrest by sex to compare to greenpoint major differenct
dfsex = df[['PERP_SEX']]

dfsex.groupby(['PERP_SEX'])['PERP_SEX'].count().sort_values(ascending=False)

# Conclusion :
NYPD's 94th Precinct which represents the North Brooklyn community of Greenpoint has had 987 arrests so far this year, the majority of which have been male *463*
and almost evenly dispersed among black, white hispanic, and white races.  The significant difference in arrest numbers between males and females is almost a seven-fold difference,
which is higher than the City as a whole at a four-fold difference.